; mid2vgm 2612 DAC Drum Map
; -------------------------
;
; Format:
;[NoteNumber] (decimal, &Hhex, &Ooctal)
;File = Wave-File (mono/stereo with 8/16 bit)
;	Note: mid2vgm 2612 automatically converts stereo -> mono, 16 -> 8 bit
;Freq = Hz (sample rate of sound, 0 defaults to is original sample rate)

; Bass Drum M
[&H23]
File = DAC\R-5 Solid Kick.wav
Freq = 0

; Bass Drum H
[&H24]
File = DAC\R-5 Dry Kick 1.wav
Freq = 0

; Rock Kit Bass Drum
;File = DAC\R-5 Room Ambient Kick 1.wav

; Side Stick
[&H25]
File = DAC\R-5 Side Stick.wav
Freq = 0

; Snare Drum M
[&H26]
File = DAC\R-5 Fat Snare.wav
Freq = 0

; Rock Kit Snare Drum
;File = R-5 Reverb Snare.wav

; Hand Clap
[&H27]
File = DAC\R-5 808 Hand Clap.wav
Freq = 0

; Snare Drum H
[&H28]
File = DAC\R-5 Tight Snare.wav
Freq = 0

; Crash Cymbal 1 (L)
[&H31]
File = DAC\R-5 Crash Cymbal.wav
Freq = 44100

; Crash Cymbal 2 (M)
[&H39]
File = DAC\R-5 Crash Cymbal.wav
Freq = 46722

; Splash Cymbal (H)
[&H37]
File = DAC\R-5 Crash Cymbal.wav
Freq = 74167

; Generic Toms (too lazy to get all the correct sample rates)

; Floor Tom L / Room Tom 1
[&H29]
File = DAC\R-5 Room Ambient Tom 1.wav

; Floor Tom H / Room Tom 2
[&H2B]
File = DAC\R-5 Room Ambient Tom 1.wav

; Low Tom / Room Tom 3
[&H2D]
File = DAC\R-5 Room Ambient Tom 1.wav

; Mid Tom L / Room Tom 4
[&H2F]
File = DAC\R-5 Dry Tom 3.wav

; Mid Tom H / Room Tom 5
[&H30]
File = DAC\R-5 Dry Tom 3.wav

; High Tom / Room Tom 6
[&H32]
File = DAC\R-5 Dry Tom 3.wav
